web-server:
  image: iitgdocker/php:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /data/php/conf.d:/data/conf.d
    - /data/php/html:/var/www/html:ro
    - /data/php/ssl:/etc/httpd/ssl:ro
    - /data/php/aide:/var/lib/aide
    - /data/php/log:/var/log/httpd
  #environment:
    #- APACHE_SERVERNAME=wingsof.chicken.com
    - MOD_SECURITY_ENABLE=1
